name: CI/CD Pipeline to Build and Deploy code to Tomcat

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set-up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build and Package with Maven
      run: mvn clean package

    - name: Verify WAR file exists
      run: ls -lh target/

    - name: Check the Tomcat Connection
      env:
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        TOMCAT_HOST: ${{ secrets.TOMCAT_HOST }}
      run: |
        curl --fail -u "$TOMCAT_USER:$TOMCAT_PASSWORD" "http://$TOMCAT_HOST:8080/manager/text/list"

    - name: Deploy WAR to Tomcat
      env:
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        TOMCAT_HOST: ${{ secrets.TOMCAT_HOST }}
      run: |
        curl -v -u "$TOMCAT_USER:$TOMCAT_PASSWORD" \
        -T target/TainBook-1.0.0-SNAPSHOT.war \
        "http://$TOMCAT_HOST:8080/manager/text/deploy?path=/TrainBook&update=true"
   

