name: Ci pipeline to build the code with maven
on:
  push:
  branches: master
jobs:
  build-deploy:
   runs-on: ubuntu-latest
   steps:
   - name: checkout code
     uses: action/checkout@v3
   - name: set-up jdk
     uses: actions/setup-java@v3
    with:
       distribution: 'temurin'
       java-version: '17' #update java version
   - name: validate with maven
     run: mvn validate
   - name: compile with maven
     run: mvn compile
   - name: test with maven
     run: mvn test
   - name: package with maven
     run: mvn package
   - name: verify WAR file 
    run: ls -lh taget/
   - name: check the tomcat connection
     run: |
            curl --fail -u "${{ secrets.TOMCAT-USER}}:${{ secrets.TOMCAT_PASSWORD }}" \
            "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/list"
  # deply to tomact
   - name: deploy war to tomcat
     run: | 
            curl -v -u ${{ secrets.TOMCAT_USER}}:${{ secrets.TOMCAT_PASSWORD }} \
            -T target/TainBook-1.0.0-SNAPSHOT.war \
            "http://{{secrets.TOMCAT_HOST}}:8080/manager/text/deoly?path=/TrainBook&update=true"
   

